name: HuHoWhiteList
version: '${version}'
main: cn.huohuas001.huhowhitelist.HuHoWhiteList
api-version: '1.16'
depend: [HuHoBot]
softdepend:
  - "PlaceholderAPI"
authors: [HuoHuas001]
description: HuHoBot Server BindQQ WhiteList
